### ISSUE TITLE
NIN structure cifar10 data

### ISSUE THREAD

**Issue by rhfa93-zz** [jiecaoyu/XNOR-Net-PyTorch#10]
hi i just wonder how can i convert normal python CIFAR-10 dataset to train_data, label and  train_data ( NIN sturcture???) if you have code about this please send it to me

**Comment by jiecaoyu** [comment]
Hi,

If you don't want to use my dateset, you can use the torchvision as shown [here](https://github.com/kuangliu/pytorch-cifar/blob/886af4caa4ee224c3fd4b42e997e43b1b4f234b9/main.py#L32-L48).

My data is from [here](https://gist.github.com/mavenlin/e56253735ef32c3c296d#descriptions). I simply convert it to numpy format so I can read it using PyTorch.

**Comment by jiecaoyu** [comment]
I am not sure about the details of how the dataset I am using is generated. But I think you can check torchvision code [here](https://github.com/pytorch/vision/blob/master/torchvision/datasets/cifar.py). It might help you understand the details.

**Comment by rhfa93-zz** [comment]
thank you so much for your help and support.

**Comment by wangtingwei1993** [comment]
I wonder if you could give me some advice about the data preprocessing if I want to use my own dataset. Thanks.

**Comment by jiecaoyu** [comment]
@wangtingwei1993 I am using the dataset from [caffe](https://gist.github.com/mavenlin/e56253735ef32c3c296d), please refer to the original Network-in-Network paper for details.
