### ISSUE TITLE
Precission for images less than batch size

### ISSUE THREAD

**Issue by Gangadhararamesh** [jiecaoyu/XNOR-Net-PyTorch#102]
hi @jiecaoyu , I have evaluated for 256,260 images ,precision values was quite good.but when i evaluated for **255 images** precision reduced abruptly,My evaluatio result are like this.

1.with 256 images
    Prec@1 54.688 Prec@5 82.422

2.with 260 images
   Prec@1 54.615 Prec@5 82.308

3.with 255 images
  Prec@1 2.353 Prec@5 21.569
  
4.with single image
  Prec1@ 100.000 Prec@5 100.000

can you please provide the solution for my problem

**Comment by jiecaoyu** [comment]
Duplicated issue.
