### ISSUE TITLE
Regarding target

### ISSUE THREAD

**Issue by Gangadhararamesh** [jiecaoyu/XNOR-Net-PyTorch#103]
hi @jiecaoyu ,
 To check the precision value I took random ,subset of Imagenet datasets for evaluation.but the target 
 and predicted value is not at all matching,target has index serially based on the no of val folder images.

can you please tell us how or where target is calculated in the code

**Comment by jiecaoyu** [comment]
Closed due to [duplicated issue](https://github.com/jiecaoyu/XNOR-Net-PyTorch/issues/106).
