### ISSUE TITLE
Computing FLOPs

### ISSUE THREAD

**Issue by shashankvkt** [jiecaoyu/XNOR-Net-PyTorch#105]
Hi,
Thank you for providing the code for XNOR net. I was just curious to know if there is a method to count the number of FLOPs the network takes for processing a single image during inference (the binarized network)? I tried using method to count FLOPs described in detectron2 (https://github.com/facebookresearch/detectron2/blob/a45600f3b1ff2c1c16ba259fcfcdaff07b629379/detectron2/utils/analysis.py), but unfortunately it could do the job correctly.
Thank you

**Comment by ciky-joh** [comment]
NIN model FLOPS is 946.7k .
NIN-XNOR model FLOPS is 3.9M. 
Why ? ?

**Comment by jiecaoyu** [comment]
Hi @shashankvkt , you can use [hooks](https://www.kaggle.com/sironghuang/understanding-pytorch-hooks) to define your own function to calculate the flops.

**Comment by shashankvkt** [comment]
Thank you @jiecaoyu
