### ISSUE TITLE
where target is calculated in your code

### ISSUE THREAD

**Issue by Gangadhararamesh** [jiecaoyu/XNOR-Net-PyTorch#106]
for images>batchsize,precision is quite good.but for images<256,precision is very bad,for img<256 target having starting index as 1 .So although prediction is proper ,while comparing prediction with target my precision is very bad .
Can i know how and where target is calculated in your code(i have added print statements in folder.pyfile but its not showing up in my output console)

**Comment by jiecaoyu** [comment]
Hi @Gangadhararamesh , could you explain more about what do you mean by ```target```?

**Comment by jiecaoyu** [comment]
Close for now. Please reopen if necessary.

**Comment by 649459021** [comment]
I think it may be target_params in util.py ?
