### ISSUE TITLE
Computation of BOPs and FLOPs

### ISSUE THREAD

**Issue by ycjing** [jiecaoyu/XNOR-Net-PyTorch#109]
Hi @jiecaoyu 

Thank you for this great work! I wonder how to compute BOPs and FLOPs of the model, so as to see how much complexities XNOR-Net has reduced. I would appreciate your help. Thank you!

Best,
Yongcheng

**Comment by jiecaoyu** [comment]
Hi @ycjing , you can use [hooks](https://www.kaggle.com/sironghuang/understanding-pytorch-hooks) to define your own function to calculate the flops for each module.

**Comment by ycjing** [comment]
Hi @jiecaoyu 

Thank you for the response! I appreciate it. I have one more quick question. Since I am not familiar with hooks, as a reference, is there any sample code that uses hooks to compute the FLOPs for each module? Thank you!

Best,
Yongcheng
