### ISSUE TITLE
LeNet arch in models/LeNet_5.py

### ISSUE THREAD

**Issue by MasonSuWei** [jiecaoyu/XNOR-Net-PyTorch#11]
Hi, the number of channels in conv1 for LeNet-5 in models/LeNet_5.py is 20. But I think conv1 in the original LeNet-5 is 6.
self.conv1 = nn.Conv2d(1, 20, kernel_size=5, stride=1)

So why the number of channels is 20 in conv1?

Can you give me some advises?

**Comment by jiecaoyu** [comment]
@MasonSuWei Hi, we are using the architecture in [caffe](http://caffe.berkeleyvision.org/gathered/examples/mnist.html). This is widely adopted as the conventional lenet-5 arch in research papers.

**Comment by MasonSuWei** [comment]
Thanks for the explanation. 
I get it now.
