### ISSUE TITLE
I think the formula which is noted is correct

### ISSUE THREAD

**Issue by lixcli** [jiecaoyu/XNOR-Net-PyTorch#117]
Hi,
I think the original formula which is noted is correct. 
Here is my demonstrate.  

Firstly, the primary formula is

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;C}{\partial&space;W_i}&space;=&space;\frac{\partial&space;C}{\partial&space;\widetilde{W_i}}&space;\times&space;(\alpha&space;\times&space;\frac{sign(W_i)}{\partial&space;W_i}&space;&plus;&space;\frac{1}{n})" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\frac{\partial&space;C}{\partial&space;W_i}&space;=&space;\frac{\partial&space;C}{\partial&space;\widetilde{W_i}}&space;\times&space;(\alpha&space;\times&space;\frac{sign(W_i)}{\partial&space;W_i}&space;&plus;&space;\frac{1}{n})" title="\frac{\partial C}{\partial W_i} = \frac{\partial C}{\partial \widetilde{W_i}} \times (\alpha \times \frac{sign(W_i)}{\partial W_i} + \frac{1}{n})" /></a>

In your formula, because each Wi in |Wi| is independent ,the formula could be transformed into

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;C}{\partial&space;W_i}&space;=&space;\frac{\partial&space;C}{\partial&space;\widetilde{W_i}}&space;\times&space;(\alpha&space;\times&space;\frac{sign(W_i}{\partial&space;W_i}&space;&plus;&space;\frac{1}{n}&space;\times&space;sign(W_i)&space;\times&space;\frac{|W_i|}{W_i})" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\frac{\partial&space;C}{\partial&space;W_i}&space;=&space;\frac{\partial&space;C}{\partial&space;\widetilde{W_i}}&space;\times&space;(\alpha&space;\times&space;\frac{\partial&space;sign(W_i)}{\partial&space;W_i}&space;&plus;&space;\frac{1}{n}&space;\times&space;sign(W_i)&space;\times&space;\frac{|W_i|}{W_i})" title="\frac{\partial C}{\partial W_i} = \frac{\partial C}{\partial \widetilde{W_i}} \times (\alpha \times \frac{sign(W_i}{\partial W_i} + \frac{1}{n} \times sign(W_i) \times \frac{|W_i|}{W_i})" /></a>

there is a absolute value in it because

<a href="https://www.codecogs.com/eqnedit.php?latex=\alpha&space;=&space;\frac{\sum&space;|W_i|}{n}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\alpha&space;=&space;\frac{\sum&space;|W_i|}{n}" title="\alpha = \frac{\sum |W_i|}{n}" /></a>

and we can get another formula by a simple demonstrate.

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{1}{n}&space;\times&space;sign(W_i)&space;\times&space;\frac{|W_i|}{W_i}=&space;\frac{1}{n}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\frac{1}{n}&space;\times&space;sign(W_i)&space;\times&space;\frac{|W_i|}{W_i}=&space;\frac{1}{n}" title="\frac{1}{n} \times sign(W_i) \times \frac{|W_i|}{W_i}= \frac{1}{n}" /></a>

So, the primary formula is correct

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;C}{\partial&space;W_i}&space;=&space;\frac{\partial&space;C}{\partial&space;\widetilde{W_i}}&space;\times&space;(\alpha&space;\times&space;\frac{sign(W_i)}{\partial&space;W_i}&space;&plus;&space;\frac{1}{n})" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\frac{\partial&space;C}{\partial&space;W_i}&space;=&space;\frac{\partial&space;C}{\partial&space;\widetilde{W_i}}&space;\times&space;(\alpha&space;\times&space;\frac{sign(W_i)}{\partial&space;W_i}&space;&plus;&space;\frac{1}{n})" title="\frac{\partial C}{\partial W_i} = \frac{\partial C}{\partial \widetilde{W_i}} \times (\alpha \times \frac{sign(W_i)}{\partial W_i} + \frac{1}{n})" /></a>

**Comment by Oslomayor** [comment]
What does it prove when you transform formula A into formula B and then back to A?

**Comment by lixcli** [comment]
The 1st formula in this issue comes from the paper, and the 2nd formula comes from the README.  This proof is used to respond to the author's statement in the readme that the gradient formula is incorrect.

**Comment by Oslomayor** [comment]
Thanks for reply! 
But, how do you get the 2nd formula?  The original formula in README is $$\frac {\partial C} {\partial W_i} = \frac {1} {n} \cdot sign(W_i) \cdot \sum _{j=1} ^n [\frac {\partial C} {\partial \widetilde {W_j} } \cdot sign(W_j)] + \frac {\partial C} {\partial \widetilde {W_i}} \cdot \frac {sign(W_i)} {\partial W_i} \cdot \alpha$$
