### ISSUE TITLE
Confusing when I printed weights

### ISSUE THREAD

**Issue by NguyenSakura** [jiecaoyu/XNOR-Net-PyTorch#120]
Dear Author,
When I run XNOR NN for LeNET, I confuse when weights are not -1 and 1 when printed. For example :
tensor([[[[-0.1221, -0.1973,  0.0049,  0.0830,  0.0083],
          [ 0.0532,  0.0953,  0.0154, -0.2182, -0.2248],
          [ 0.0594,  0.0664, -0.1902, -0.3897, -0.7412],
          [-0.1384, -0.1770, -0.2178, -0.6822, -0.4979],
          [ 0.0176,  0.0096, -0.2161, -0.4323,  0.1316]],

**Comment by tehtea** [comment]
The weights you're printing are the ones used during training (called latent weights, based on this paper: https://arxiv.org/abs/1906.02107). You have to call `bin_op.binarization()` with the latent weights to binarize them.

**Comment by NguyenSakura** [comment]
I got it. Thanks for the quick reply.

Vào CN, 18 thg 4, 2021 vào lúc 15:44 Jing Wei ***@***.***>
đã viết:

**Comment by NguyenSakura** [comment]
Could you help me how to call binarized weights. I tried but not
successful . Many thanks
print(model.state_dict().keys())
w0 = model.state_dict()["bin_conv2.bn.weight"]

Vào Th 2, 19 thg 4, 2021 vào lúc 09:15 jONE NGUYEN ***@***.***>
đã viết:

**Comment by jiecaoyu** [comment]
@NguyenSakura , please check [this line](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/ebccb503b2f9ebc96187a75b6daa63d95b61d110/ImageNet/networks/main.py#L244).

**Comment by NguyenSakura** [comment]
Many thanks for  yours answers. I fixed it and I got binarized weights.
But, I found that weights in  the first , and last layer are not binarized.
Then, I modified here :
       start_range = 1
        end_range = count_targets-1
        self.bin_range = numpy.linspace(start_range,
                end_range, end_range-start_range+1)\
                        .astype('int').tolist()
I got binarized weights in the last layer. But weights in the first layer
are still not binarized. I continued to modify many ways but not a success
:


Vào Th 2, 19 thg 4, 2021 vào lúc 11:14 Jiecao Yu ***@***.***>
đã viết:
