### ISSUE TITLE
what's the difference between your dataset and the offical(CIFAR)

### ISSUE THREAD

**Issue by flygyyy** [jiecaoyu/XNOR-Net-PyTorch#15]
As I didn't see you use Normalize in your code, can you explain the details?

**Comment by jiecaoyu** [comment]
@flygyyy To make a fair comparison between XNOR-Net and the floating-point version, I am using the preprocessed data as the same in another other [repo](https://github.com/jiecaoyu/pytorch-nin-cifar10).

**Comment by flygyyy** [comment]
Thanks.
