### ISSUE TITLE
train on custom data

### ISSUE THREAD

**Issue by ajajar** [jiecaoyu/XNOR-Net-PyTorch#18]
Hey, 

I was wondering if it s possible to train XNOR-Net-PyTorch on custom data ? I would appreciate your help.

Best regards

**Comment by jiecaoyu** [comment]
Hi @ajajar , if you already have a DNN model in floating-point numbers, a simple strategy is to replace the convolutional layers with the BinConv layer [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/7f84f1bf6921bc99b05bbc869dddf2bd64989a40/ImageNet/networks/model_list/alexnet.py#L26). Also you need to chage the traning/testing steps as shown [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/7f84f1bf6921bc99b05bbc869dddf2bd64989a40/ImageNet/networks/main.py#L218).

**Comment by ajajar** [comment]
@jiecaoyu many thanks , I will give it a try
