### ISSUE TITLE
TypeError: clamp() got an unexpected keyword argument 'out'

### ISSUE THREAD

**Issue by MrLinNing** [jiecaoyu/XNOR-Net-PyTorch#22]
When i run this code, problem happen, and how to solved this problem.
My python version is 2.7, thank you !
```
cd <Repository Root>/MNIST/
python main.py
```
```
File "/pytorch_test/XNOR-Net-PyTorch/MNIST/util.py", line 46, in clampConvParams
out = self.target_modules[index].data)
TypeError: clamp() got an unexpected keyword argument 'out'
```

**Comment by JingliangGao** [comment]
@jiecaoyu

**Comment by jiecaoyu** [comment]
@MrLinNing @JingliangGao Hi, try to replace

```python
self.target_modules[index].data.clamp(-1.0, 1.0,
                    out = self.target_modules[index].data)
```
with
```python
self.target_modules[index].data = self.target_modules[index].data.clamp(min=-1.0, max=1.0)
```

**Comment by MrLinNing** [comment]
Thank you! @jiecaoyu 
 I have the imagenet folder like the following, and How to train the imagenet example? I have already install caffe. 
![image](https://user-images.githubusercontent.com/24288811/39793269-4ad4a66c-5377-11e8-8855-ab4f77bda733.png)

**Comment by jiecaoyu** [comment]
@MrLinNing Hi, please use the [```--data```](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/7f84f1bf6921bc99b05bbc869dddf2bd64989a40/ImageNet/networks/main.py#L33) option to specify the data folder path and it should be ready to go.

**Comment by agnonchik** [comment]
I replaced 

self.target_modules[index].data.clamp(-1.0, 1.0,
                    out = self.target_modules[index].data)
with

self.target_modules[index].data = self.target_modules[index].data.clamp(min=-1.0, max=1.0)
 
but got another error:

Traceback (most recent call last):
  File "main.py", line 189, in <module>
    train(epoch)
  File "main.py", line 37, in train
    bin_op.binarization()
  File "/home/val/src/pytorch/XNOR-Net-PyTorch/MNIST/util.py", line 34, in binarization
    self.binarizeConvParams()
  File "/home/val/src/pytorch/XNOR-Net-PyTorch/MNIST/util.py", line 64, in binarizeConvParams
    .mul(m.expand(s), out=self.target_modules[index].data)
TypeError: mul() received an invalid combination of arguments - got (Tensor, out=Tensor), but expected one of:
 * (Tensor other)
 * (float other)

**Comment by jiecaoyu** [comment]
@agnonchik it is the exact same syntax error. Please make the same update.

**Comment by agnonchik** [comment]
Yeah, a similar replacement fixed the issue.
Does Python 3 tolerate this syntax "out="?

**Comment by jiecaoyu** [comment]
@agnonchik I think it is due to the API change in PyTorch, not python3.

**Comment by agnonchik** [comment]
Has anyone tested XNOR-Net with Python 3? I tried it and got a bunch of errors.

**Comment by jiecaoyu** [comment]
@agnonchik It should only contain syntax errors. There is no api difference.
