### ISSUE TITLE
Mismatch of equation(12) and code

### ISSUE THREAD

**Issue by CNSaintNeo** [jiecaoyu/XNOR-Net-PyTorch#25]
Thanks for your great job.
But I am confused of the code to achieve equation(12).
In your code, sign(Wi)'/Wi'=0 if |Wi|>1, sign(Wi)'/Wi'=1 if |Wi|<1. It doesn't match the function sign(Wi)'/Wi'=0 if Wi !=0. Is it just a Approximation?

**Comment by jiecaoyu** [comment]
yes, sign() function is not differentiable

**Comment by CNSaintNeo** [comment]
another question, in your code self.target_modules[index].grad.data = m.add(m_add).mul(1.0-1.0/s[1]).mul(n), your explanation said to make the new gradients the same range as the original gradients. But from the equation there is no need to multiply n. 
Which procedure cause the different range problem?

**Comment by jiecaoyu** [comment]
@CNSaintNeo I guess, with adam solver, multiplying all gradients with the same number is to solve the precision problem of adam solver.
