### ISSUE TITLE
Confusion in notes

### ISSUE THREAD

**Issue by akhauriyash** [jiecaoyu/XNOR-Net-PyTorch#26]
Hello! 
I was attempting to understand your notes on Backward Gradient of Scaled Sign Function.
What is the bold W? Are those _all_ the parameters of the network? (Assuming a fully connected network.)
**W** = [W1, W2,..., Wn]
Here, does the Wk denote a specific layer (kth layer) from the network? (k being any number from 1 to n)
Equation 4 seems to lead me to think that **W** is the weight for a specific layer, and Wi is the ith element from the **W** matrix. 
I am pretty sure the **W** consists of all the layers, but honestly I want to be certain.
I ask because it is causing some ambiguity in the later equations. 

Would really appreciate the help! 
Thanks.

**Comment by jiecaoyu** [comment]
@akhauriyash  Hi, **W** is for one kernel/filter.

**Comment by akhauriyash** [comment]
This is great, I understand it perfectly now. 
This is awesome work! 💯 
Cheers!
