### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Paul0629** [jiecaoyu/XNOR-Net-PyTorch#27]
You rewrite the torchvision.datasets in your data.dataset. why don't you use torch.datasets.CIFAR10 directly? What 'train_data' and 'train_labels' are, where do I get them. My CIFAR10 dataset is not like that.

**Comment by jiecaoyu** [comment]
Hi @Paul0629 , please check [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch#cifar-10) to download the dataset. This dataset is preprocessed and, therefore, can help NIN reach the reported accuracy.
