### ISSUE TITLE
TypeError: expected a readable buffer object

### ISSUE THREAD

**Issue by andeyeluguo** [jiecaoyu/XNOR-Net-PyTorch#3]
File "pytorch-master/XNOR-Net-PyTorch-master/ImageNet/networks/../datasets/folder.py", line 125, in __getitem__     datum.ParseFromString(value) 

what occurs this error?
ps: I use the imagenet dataset which comes from the caffe ilsvrc12_train_lmdb and ilsvrc12_val_lmdb

**Comment by andeyeluguo** [comment]
I see your dataset in google driver.but I can't access it because i am in  China.Do you use the dataset of  ilsvrc12 which can be used in caffe ? Thank you .

**Comment by jiecaoyu** [comment]
@andeyeluguo Yes, I am using the lmdb dataset generate within Caffe. However, I use the [```fix_key.sh```](https://github.com/jiecaoyu/pytorch_imagenet/tree/master/tools) script to fix the key for accessing in PyTorch.

I am not sure about the error. Could you copy the whole error message? And could help print the type of ```value``` by

```python
print(type(value))
```

**Comment by andeyeluguo** [comment]
the information is like this ：

the code in folder.py is 
'''
 key_index ='{:08}'.format(index)
        print key_index
        print type(key_index)
        value = lmdb_cursor.get(key_index)
        print value
        print type(value)
'''

the error information is like this:
'''
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    main()
  File "main.py", line 184, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 213, in train
    for i, (input, target) in enumerate(train_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "pytorch-master/XNOR-Net-PyTorch-master/ImageNet/networks/../datasets/folder.py", line 126, in __getitem__
    datum.ParseFromString(value)
TypeError: expected a readable buffer object

00002560
<type 'str'>
None
<type 'NoneType'>
00002816
<type 'str'>
None
<type 'NoneType'>
00003072
<type 'str'>
None
<type 'NoneType'>
00003328
<type 'str'>
None
<type 'NoneType'>
00003584
<type 'str'>
None
<type 'NoneType'>
00003840
<type 'str'>
None
<type 'NoneType'>
00004096
<type 'str'>
None
<type 'NoneType'>

'''
if I want to directly use the lmdb database which is used in caffe ,what should I do ?
Maybe I should merge the convert_key.py into the folder.py ? thank you.

**Comment by andeyeluguo** [comment]
I run the your script to process the dataset,and it can skip the error. 
Then i see the new error
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:66
try to make the batch_size small.

however,i meet other error that maybe caused by the distribute mode use.
what should I do to only use the one device.

**Comment by jiecaoyu** [comment]
Hi, the error message you showed means your GPU doesn't have enough memory space.

If you want to force it to run on one device, you can simply remove all "distribute" code. I only used one machine to train the network.

I am using a 4-GPU machine to train the network and the default setting uses as many as GPUs it can detect. To force it to use only one GPU, delete the [line 88](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/8713886a3d085cc3572a99d6dcbe687e8020e451/ImageNet/networks/main.py#L88).

**Comment by andeyeluguo** [comment]
I change the line 88 into "model = torch.nn.DataParallel(model, device_ids= range(1)) " ,and it can run in one device.

**Comment by ujsyehao** [comment]
@andeyeluguo @jiecaoyu Hi, I meet the error too, "in __getitem__ datum.ParseFromString(value), TypeError: expected a readable buffer object"
I use the fix_key.sh successfully, but it still has the error, Can you give me some advice?
