### ISSUE TITLE
what is your version of pytorch

### ISSUE THREAD

**Issue by andeyeluguo** [jiecaoyu/XNOR-Net-PyTorch#30]
I just got the error "ImportError: No module named distributed" when I 
import torch.utils.data.distributed

**Comment by jiecaoyu** [comment]
@andeyeluguo Hi, you can directly remove all ```distributed``` related instructions.

**Comment by huwade** [comment]
Hi, my pytorch version is 0.3.0, and python version is 3.6. I got the error 
File "main.py", line 149, in <module>
    model = models.LeNet_5()
  File "/home/iis519/samba/wade/XNOR-Net-PyTorch/MNIST/models/LeNet_5.py", line 75, in __init__
    previous_conv=True, size=4*4)
  File "/home/iis519/samba/wade/XNOR-Net-PyTorch/MNIST/models/LeNet_5.py", line 45, in __init__
    self.bn = nn.BatchNorm2d(input_channels/size, eps=1e-4, momentum=0.1, affine=True)
  File "/home/iis519/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 18, in __init__
    self.weight = Parameter(torch.Tensor(num_features))
TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (float)
 * (torch.FloatTensor viewed_tensor)
      didn't match because some of the arguments have invalid types: (float)
 * (torch.Size size)
      didn't match because some of the arguments have invalid types: (float)
 * (torch.FloatStorage data)
      didn't match because some of the arguments have invalid types: (float)
 * (Sequence data)
      didn't match because some of the arguments have invalid types: (float)
Can you tell me about you environment? 
thanks

**Comment by jiecaoyu** [comment]
@huwade Hi, I am using Python 2.7 and pytorch 0.5.0. I haven't seen your error before.
