### ISSUE TITLE
Scaling binarized activations.

### ISSUE THREAD

**Issue by bhargavajs07** [jiecaoyu/XNOR-Net-PyTorch#31]
Hi, I could not find where you are scaling the binarized input activations with their l1 norm. In the BinActive function you just call the sign function which is just directly used to the fwd pass.  Could you please point me to where the scaling is happening.
In case you felt it wasn't necessary  could you please tell why?

Thanks!

**Comment by GrimReaperSam** [comment]
Hi,

I was also looking at this problem recently. If you go back to the original paper, the authors say that the input scaling factor doesn't affect the results too much, and they decided to implement without it for efficiency reasons.
You can check that at page 12, in the paragraph discussing Table 1: 
"""
We found that the scaling factors for the weights (α) is much
more effective than the scaling factors for the inputs (β). Removing β reduces the accuracy
by a small margin (less than 1% top-1 alexnet).
"""

Enjoy!

**Comment by bhargavajs07** [comment]
Thanks for pointing out!!
