### ISSUE TITLE
A typo in README

### ISSUE THREAD

**Issue by HolmesShuan** [jiecaoyu/XNOR-Net-PyTorch#33]
The second term of `the correct backward gradient` in `Notes` should be 
![equation](http://latex.codecogs.com/gif.latex?\frac{\partial{C}}{\partial{\widetilde{W_i}}}\cdot\frac{\partial{sgn(W_i)}}{\partial{W_i}}\cdot\alpha).
Also, since ![equation](http://latex.codecogs.com/gif.latex?\frac{\partial{sgn(x)}}{\partial{x}}=0,x\neq{0}), why not further simplify the equations? Did I miss something?

**Comment by jiecaoyu** [comment]
Please check section 1.3 in [this paper](https://arxiv.org/pdf/1602.02830.pdf). It provides a better explanation.
