### ISSUE TITLE
Question about the LeNet_5 used in the MNIST training

### ISSUE THREAD

**Issue by Sanghyun-Hong** [jiecaoyu/XNOR-Net-PyTorch#35]
Hello, I wonder if this network implementation is correct, since the block structure for the XNOR-Net in the original paper is like BNorm -> BinActive -> BinConv -> Pool. However, I couldn't find such sequences.

Thanks,
S.

**Comment by jiecaoyu** [comment]
I think Pool is optional and other functions are implemented [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/7f84f1bf6921bc99b05bbc869dddf2bd64989a40/MNIST/models/LeNet_5.py#L51)
