### ISSUE TITLE
L1 conv issues

### ISSUE THREAD

**Issue by zackhan64** [jiecaoyu/XNOR-Net-PyTorch#36]
Hey @jiecaoyu ,
       Thanks for your great work and sharing it.
       I have a question about the LeNet_5 implementation. At line 12 in your util.py code, you set start_range =1 and end_range=count_targets-2. If my understanding is right, you mean here that the second conv layer(size:[20, 50, 5, 5 ]) and the first fc layer (size:[500, 800]) are binarized. When I set end_range = count_targets-1, I can binarize the second fc layer, and the accuracy degrades only a little(<1%). However, when I set start_range = 0, which means the first conv layer is binarized, the accuracy is kept at a low level.
       Is it possible to binarize the first conv layer using your code? if is, could tell me how to binarize the first conv layer. Thanks for your sharing again.

**Comment by jiecaoyu** [comment]
@zackhan64 Hi, usually the first layer is not binarized. The first layer can be considered as a very low-level feature extractor and binarizing it will destroy all low-level features.

**Comment by zackhan64** [comment]
Thanks for the reply! @jiecaoyu
