### ISSUE TITLE
Is this the implementation of BNN or XNOR ?

### ISSUE THREAD

**Issue by kakaxi314** [jiecaoyu/XNOR-Net-PyTorch#4]
I look from your readme the accuracy is similar to the XNOR.
In XNOR forward path, The conv should be $(sign(I)\circledast sign(W)) \odot K \alpha$
But in your code, I don't find the calculation of $K$. And the input to conv layer is binary tensor.
Is this my misunderstanding?

**Comment by jiecaoyu** [comment]
@kakaxi314 as commented [here](https://github.com/allenai/XNOR-Net/issues/4#issuecomment-239088696), the scaling factor for the input tensor is actually not important and cannot improve the accuracy.

**Comment by kakaxi314** [comment]
@jiecaoyu Thanks, But I recently read this paper 'Performance Guaranteed Network Acceleration via High-Order Residual Quantization'. Maybe in High-Order Quantization condition, the scaling factor for the input tensor is useful. I will try to implement it. Once again, thanks for your reply.
