### ISSUE TITLE
XNOR-net for mnist

### ISSUE THREAD

**Issue by Karry11** [jiecaoyu/XNOR-Net-PyTorch#42]
Hi，thanks for your great job first！after I read your pytorch code，I find you didnt do xnor-net for mnist，you just finish BWN for mnist.Is it？

**Comment by jiecaoyu** [comment]
@Karry11 weights are binarized [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/26cca8cc793802f72b5ef2e5a2a823536a4abae8/MNIST/main.py#L37)

**Comment by jiecaoyu** [comment]
Hi @Karry11 , inputs are binarized [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/26cca8cc793802f72b5ef2e5a2a823536a4abae8/MNIST/models/LeNet_5.py#L53)

**Comment by Karry11** [comment]
Thanks a lot，I have another question ，when I print the tensor（weight params）from bn_conv1，it is float number，not 1
or -1，was I wrong？
