### ISSUE TITLE
AutoGrad (gradcheck) on BinActive

### ISSUE THREAD

**Issue by akhauriyash** [jiecaoyu/XNOR-Net-PyTorch#43]
```
class BinActive(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        size = input.size()
        input = input.sign()
        mean = abs(input).mean()
        return mean*input
    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input.ge(1)] = 0
        grad_input[input.le(-1)] = 0
        p2_f = grad_input.abs().mean()*grad_input
        p1_f = grad_input.sign()*(1/grad_input.nelement())
        grad_input = p1_f + p2_f
        return grad_input
```

`x = torch.randn(52, 24, requires_grad=True)
`
`
binactive = BinActive.apply
`
`res = torch.autograd.gradcheck(binactive, (x,), atol=1e-2)`

After running the following code, I get res as True.
Whereas, the BinActive code in this implementation does not work with gradcheck.
Am I correct to say that the BinActive backward propogation in this implementation is an approximation, and for this reason it does not work with gradcheck?
I tried to re-derive the backward propogation from your notes and code out the backward method myself.
This is not specifically an issue, but a general doubt.

Would appreciate your comments on this matter!

P.S. I understand that you haven't multiplied the mean in the forward, but I just wanted to get it working with gradcheck for my own satisfaction.

Thanks.

**Comment by jiecaoyu** [comment]
@akhauriyash Hi, I wonder what do you mean by "this implementation does not work with gradcheck" ? Does it return an error or return False?

**Comment by akhauriyash** [comment]
It returns an error, there is a Jacobian mismatch. That essentially means its False for the given tolerance. (This implementation = This repository)

BinActive() in this repository returns false for any atol < 1.

The implementation of BinActive() I have raised above returns True for atol > 1e-2.

I am a little confused if gradcheck verification should matter here, as this BinActive() layer essentially approximates the input matrix.
