### ISSUE TITLE
LeNet-5 - MNIST structure is unlike the paper?

### ISSUE THREAD

**Issue by akhauriyash** [jiecaoyu/XNOR-Net-PyTorch#48]
Hello,
I am confused, is the LeNet-5 implementation the same as those available online?
[https://cdn-images-1.medium.com/max/800/1*yXjgC7PFTxb-Oi_L_hoFXA.png](Image)
This is different from the LeNet-5 seen in your repository. 
Kindly clarify.

P.S. By 'the paper', I refer to this [http://yann.lecun.com/exdb/publis/pdf/lecun-01a.pdf](image)
Thanks!

**Comment by jiecaoyu** [comment]
I am using the structure as in [Caffe](https://github.com/BVLC/caffe/blob/master/examples/mnist/lenet.prototxt)
