### ISSUE TITLE
Why not binary the parameters of the first and the last conv layer?

### ISSUE THREAD

**Issue by wyf0912** [jiecaoyu/XNOR-Net-PyTorch#50]
https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/26cca8cc793802f72b5ef2e5a2a823536a4abae8/CIFAR_10/util.py#L12-L28

**Comment by jiecaoyu** [comment]
Binarizing the first and the last layer will cause a large accuracy loss.
