### ISSUE TITLE
How have the ImageNet accuracies been reported?

### ISSUE THREAD

**Issue by akhauriyash** [jiecaoyu/XNOR-Net-PyTorch#51]
In the log.baseline file, I observe that the accuracies reach Prec@1 50.781 (47.435)	Prec@5 73.047 (72.800) and so on. However, in your repository it says you have achieved :
Top-1: 44.87% Top-5: 69.70%

I apologize if this is a very trivial doubt, but how does one report the model accuracy? Is it not the highest accuracy achieved in all iterations?  

Thank you!

**Comment by jiecaoyu** [comment]
Can you point out where you see these numbers? I guess you are probably looking at log info of the training part, not the validation part.
