### ISSUE TITLE
Weights not binary

### ISSUE THREAD

**Issue by shashankvkt** [jiecaoyu/XNOR-Net-PyTorch#52]
Hello,
Thank you very much for providing the code. Just out of curiosity, I wanted to visualize the weight values and see if they are of {-1,1}, but unfortunately I found that they still are real-valued.  
Could you kindly guide me on this? I used `model.bin_ip1.state_dict()` and similarly for conv2 but they values are of real-value range and not binary.

**Comment by jiecaoyu** [comment]
First, you need to perform the [binarization](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/26cca8cc793802f72b5ef2e5a2a823536a4abae8/MNIST/main.py#L60) before you fetch the weights.

Second, using a simple example, you might see numbers like {-0.517, 0.517, 0.517}. But it is actually 0.517 * {-1, 1, 1} which is binary.

**Comment by shashankvkt** [comment]
Thank you very much for your feedback. Just summarizing what youve said, should it be like  
 `1. bin_op.binarization()`  
 `2. print(model.bin_ip1.state_dict(`))   
Kindly advice? Thanks

**Comment by jiecaoyu** [comment]
Yes, let me know if you still dont get the numbers

**Comment by shashankvkt** [comment]
Amazing...Thanks a lot for your feedback.!! It worked!!

**Comment by shashankvkt** [comment]
Hi, 
I have a follow up question on this. What if I'd like the weights to be {-1,1} rather than floatingpoint*{-1,1}?  
Would that be possible?
