### ISSUE TITLE
batchnorm.py Error

### ISSUE THREAD

**Issue by mohendra** [jiecaoyu/XNOR-Net-PyTorch#53]
\batchnorm.py", line 21, in __init__
    self.weight = Parameter(torch.Tensor(num_features))
TypeError: new(): data must be a sequence (got float)

**Comment by jiecaoyu** [comment]
@mohendra Hi, could you help check your PyTorch version? I don't see this error with the newest version.

**Comment by aab60526** [comment]
Hi jiecaoyu,
my pytorch version is 1.0.0 and I still got this problem.
self.weight = Parameter(torch.Tensor(num_features))
TypeError: new(): data must be a sequence (got float)

**Comment by jiecaoyu** [comment]
@aab60526 Hi, can you post the entire error information? I don't know where the error came from.

**Comment by aab60526** [comment]
Hi jiecaoyu,
Thanks,I have solved the problem.
this is because division difference between python2 and python3,
\LeNet_5.py", line 45
self.bn = nn.BatchNorm2d(input_channels//size, eps=1e-4, momentum=0.1, affine=True)
should use '//' to avoid (float) type.
