### ISSUE TITLE
What pre-processing has been done on the CIFAR-10 dataset?

### ISSUE THREAD

**Issue by akhauriyash** [jiecaoyu/XNOR-Net-PyTorch#54]
> You can download the training and validation datasets here and uncompress the .zip file. 

In the CIFAR-10 dataset you have provided, what changes have been made? Has the data been standardized or does it also have preprocessing like global contrast normalization and ZCA whitening as done in the BinaryConnect paper?

You mention:  To make a fair comparison between XNOR-Net and the floating-point version, I am using the preprocessed data as the same in another other repo.

However, I still do not know what preprocessing has been performed on the data in the other repository either.

Thanks!

**Comment by jiecaoyu** [comment]
@akhauriyash Hi, I am using the dataset from [caffe](https://gist.github.com/mavenlin/e56253735ef32c3c296d), please refer to the original Network-in-Network paper for details.
