### ISSUE TITLE
Two non-linearity functions in the forward path

### ISSUE THREAD

**Issue by mil-ad** [jiecaoyu/XNOR-Net-PyTorch#55]
I may be wrong but shouldn't binary activation replace ReLU as the non-linearity in the forward path? How come your implementation has both ReLU _and_ bin activations?

**Comment by jiecaoyu** [comment]
Hi @mi-lad , as discussed in the original paper, "We can insert a non-binary activation(e.g.,ReLU) after binary convolution. This helps when we use state-of-the-art networks (e.g.,AlexNet or VGG)."
