### ISSUE TITLE
Confused about two methods in CIFAR_10/util.py

### ISSUE THREAD

**Issue by dsfour** [jiecaoyu/XNOR-Net-PyTorch#58]
Hi, thank you for your effort in implementing xnornet. I am confused about two methods meancenterConvParams(self) and updateBinaryGradWeight(self) in https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/master/CIFAR_10/util.py.
1. What is method meancenterConvParams(self) for? I have not seen the corresponding operation in paper of XNORNet.
![1](https://user-images.githubusercontent.com/19569952/49325058-9fc16d80-f576-11e8-86e5-74dc342d598b.png)

2. I think the last line of method meancenterConvParams(self) does not conform the backward gradient described in https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/master/notes/notes.pdf. Can you help to explain these? Thanks a lot. 
![2](https://user-images.githubusercontent.com/19569952/49325060-a354f480-f576-11e8-87fa-8e1e26a98df2.png)
![3](https://user-images.githubusercontent.com/19569952/49325061-a64fe500-f576-11e8-92fe-557f554e49a9.png)

**Comment by jiecaoyu** [comment]
Hi @dsfour , sorry for late reply. I was working on a paper submission.

I am not sure why ```meancenterConvParams()``` is used. But it does help improve the accuracy in some cases. It is also not mentioned in the paper and I guess it is a small trick.

For ```.mul(1.0-1.0/s[1]).mul(n)```, please refer to my answer [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/issues/28#issuecomment-401885963)。
