### ISSUE TITLE
Hi, If I have got the Imagenet data by caffe, how can I use it for  Pytorch

### ISSUE THREAD

**Issue by flygyyy** [jiecaoyu/XNOR-Net-PyTorch#6]
when I compile the alexnet code, I meet the following error. my directory is ilsvrc12_train_lmdb and ilsvrc12_val_lmdb both directory  has a  data.mdb and lock.mdb, can I change it for pytorch?

Traceback (most recent call last):
  File "main.py", line 27, in <module>
    import datasets as datasets
  File "/home/yy/XNOR-Net-PyTorch-master/ImageNet/networks/../datasets/__init__.py", line 1, in <module>
    from .folder import ImageFolder
  File "/home/yy/XNOR-Net-PyTorch-master/ImageNet/networks/../datasets/folder.py", line 6, in <module>
    import lmdb
ImportError: No module named lmdb

**Comment by jiecaoyu** [comment]
Hi,

There are two options:

1. Install Caffe following the instructions on [this page](http://caffe.berkeleyvision.org/install_apt.html). This will actually be the simplest way considering you already download the data. The error message shows that you didn't have lmdb on your machine. Following those instructions will help you install all packages you need.

2. You can use the torchvision package but you need to download the raw data again. To do that, follow the instructions [here](http://pytorch.org/docs/master/torchvision/datasets.html#imagenet-12). Basically, you need to replace [my instructions](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/7f84f1bf6921bc99b05bbc869dddf2bd64989a40/ImageNet/networks/main.py#L136-L163) with the instructions [here](https://github.com/bearpaw/pytorch-classification/blob/cb5431ee091ec5e6f5225eb5bff7b918248b31d6/imagenet.py#L118-L141). But before that, you have to download and preprocess the data as described [here](https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#download-the-imagenet-dataset)

I recommend you to take the first option. The torchvision data loader is slow if you don't have a large SSD. And downloading the raw data will take tons of time.
