### ISSUE TITLE
Question about update binary gradient formular

### ISSUE THREAD

**Issue by haithanhp** [jiecaoyu/XNOR-Net-PyTorch#61]
Dear @jiecaoyu,

Thanks for your great implementation of XNOR-Net. I see your modification in updating binary gradient but why do we have the following inference?

<img width="471" alt="screen shot 2019-01-26 at 11 44 25 am" src="https://user-images.githubusercontent.com/25809722/51790243-5e0d0780-2160-11e9-8314-027c1790ddce.png">

I think the sum of the whole equals the sum of each part in the bracket. so why the sum of the second term is able to be removed? Could you clarify your formula there?

Thanks,
Hai

**Comment by jiecaoyu** [comment]
Hi @HaiPhan1991 , the partial derivative from ```sign(W_j)``` to ```W_i``` equals to 0 for ```j != i```. Therefore, the second term for ```j != i``` equals to 0.

**Comment by haithanhp** [comment]
I see. Thank you, @jiecaoyu. It is very helpful.
