### ISSUE TITLE
About Binary Weight network

### ISSUE THREAD

**Issue by dudqls1994** [jiecaoyu/XNOR-Net-PyTorch#64]
Hello !! 
Thank you for giving your xnor code!!
Do you know how to do binary weight network ?

In xnor paper, binary weight network get better accuracy than xnor network. 
So  I want to how to write binary weight network !! 

And , how to calculate memory and speed in this network .
Thank you !

**Comment by jiecaoyu** [comment]
Hi @dudqls1994 ,

For binary weight networks, you can simply remove the [```BinActive()```](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/834cb6cf32e476f318a48ec73fe19d16058e2470/ImageNet/networks/model_list/alexnet.py#L51) function.

For memory and speed, this repo is only for training the binary networks but not inference. Therefore, you cannot measure the required memory and achievable speed directly.

Thanks!
