### ISSUE TITLE
About the value in BinConv, is not the 1 or -1?

### ISSUE THREAD

**Issue by HymEric** [jiecaoyu/XNOR-Net-PyTorch#66]
When I have trained the net, I look at the inner value of BinConv. But the value is not 1 or -1? Why? Please, if you have time, give me an answer. Thank you!

**Comment by jiecaoyu** [comment]
hi @HymEric , if you look at the weights after [```bin_op.binarization()```](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/834cb6cf32e476f318a48ec73fe19d16058e2470/ImageNet/networks/main.py#L244), you can find the weights are binary. Remember that [0.3, -0.3] is actually binary as 0.3 * [1, -1].

**Comment by HymEric** [comment]
> hi @HymEric , if you look at the weights after [`bin_op.binarization()`](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/834cb6cf32e476f318a48ec73fe19d16058e2470/ImageNet/networks/main.py#L244), you can find the weights are binary. Remember that [0.3, -0.3] is actually binary as 0.3 * [1, -1].

thank your reply. But the final model don't save the binary value in conv layer. The a*B will be calculated until the model have loaded and used. So, the model really is a binary model (BNN)?

**Comment by jiecaoyu** [comment]
@HymEric This framework is for training the binary model.
