### ISSUE TITLE
Question about the corrected gradients

### ISSUE THREAD

**Issue by jxgu1016** [jiecaoyu/XNOR-Net-PyTorch#69]
As is mentioned in the previous issue #1, you corrected the formula of the gradients, which I totally agree on. But if you treat the $W_i$s as a whole ($W$ with a dim like N_out, N_in, kH, kW), the gradients will be exactly the same as the one mentioned in the XNOR paper. How to explain  that?

**Comment by jiecaoyu** [comment]
Hi @jxgu1016 , I am sorry but I cannot understand your question. It will be better if you can show the steps of calculation.

I think you are doing something wrong with the gradient from a scale to a vector.

**Comment by jxgu1016** [comment]
Thanks for your quick reply! Let me make it more clear:
1. In XNOR Net, there are several $\alpha$s in each layer (see Algorithm 1), so the gradients are correct in that case. 
2. But it's hard to accelerate the inference process, and we need **one** layer-wise $\alpha$, which is exactly what we are discussing about. In such case, your corrected gradients looks correct.
3. Actually, $W$ is a tensor with 4 dimension, we can always directly calculate its gradient, instead of calculating each $W_i$. Try and you will find the problem.

**Comment by jiecaoyu** [comment]
Hi @jxgu1016 , actually you can write down the steps and take a picture. I think it will help a lot.

First, $\alpha$ is not layer-wise but for weights belonging to the same output channel.

Second, assume ```Q``` is the quantized weights. We can rearrange ```Q``` and ```W``` into 1-D vectors. Assume each vector has ```n``` elements. Here, the gradient from ```Q``` to ```W``` should be a ```n```x```n``` matrix and you will end up with the same result as I get.

**Comment by jxgu1016** [comment]
Thanks for your patience but you make me confused, totally. Ok, let's first focus on the ```\alpha```:

1. You mean there are multiple ```\alpha```s in each layer, so the ```\alpha``` in Eqs. 3,4,5 in [notes.pdf](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/master/notes/notes.pdf) should be ```\alpha_i```.
2. Then in Eq. 12 for j != i, the gradients from ```\alpha_j``` to ```W_i``` will be zero. Because ```W_i``` do not participate in the calculation of ```\alpha_j``` (j != i).

Please correct me if I am wrong.

**Comment by jiecaoyu** [comment]
@jxgu1016 
Weight is a 4D tensor. Assume it has a size of NxCxRxS. (N/C is output/input channels, R/S is the kernel width/height). Each ```\alpha``` is shared for CxRxS weights. Each layer has ```N``` ```\alpha``` values. The equations in the notes focus on one weight filer (CxRxS).

**Comment by jxgu1016** [comment]
Thanks again. I was misled by the notation in Eq. 1 that ```W_i``` is actually a scalar not a matrix or tensor. And here is a piece of advice: for scalar, plz use ```w_i```.

**Comment by jiecaoyu** [comment]
@jxgu1016 Thanks for your advice!

**Comment by thanhdao** [comment]
Hi Jiecaoyu,
Thank you for your sharing. Could you please tell me how can you have this formula:
https://user-images.githubusercontent.com/3870854/56213367-d8ca2c80-6096-11e9-921e-07afabae5deb.png

Thank you very much

**Comment by jiecaoyu** [comment]
@thanhdao It is based on the chain rule of the gradient.

**Comment by thanhdao** [comment]
@jiecaoyu  Yes, but I never see the chain rule formula like that. Could you tell me how to find it in any books? I can not figure out how are is it. I just know the chain rule in (9) equation bellow
![chainrule](https://user-images.githubusercontent.com/3870854/56400300-26f55080-628e-11e9-9bce-8f3849882f57.PNG)

**Comment by jxgu1016** [comment]
@thanhdao That's because $W_i$ participates in multiple "chain"s and we should add them all.

**Comment by thanhdao** [comment]
@jxgu1016 But how do you know it participates in multiple chains. Based on 2 equation below? 
![xnornet](https://user-images.githubusercontent.com/3870854/56402360-fd412700-6297-11e9-8844-9d4b15b0a2d1.PNG)
![xnornet2](https://user-images.githubusercontent.com/3870854/56402361-fd412700-6297-11e9-8dd5-0fba9fea5d3b.PNG)

**Comment by jxgu1016** [comment]
@thanhdao As $alpha$ is a scalar and when multiplied with a matrix $sign(W)$, it will be broadcast to a matrix. That's where multiple chains come from.

**Comment by thanhdao** [comment]
@jxgu1016 Thank you so much
