### ISSUE TITLE
about updateBinaryGradWeight

### ISSUE THREAD

**Issue by ysymyth** [jiecaoyu/XNOR-Net-PyTorch#70]
I have a question about the last two lines:
```
self.target_modules[index].grad.data = m.add(m_add).mul(1.0 - 1.0 / s[1]).mul(n)
self.target_modules[index].grad.data = self.target_modules[index].grad.data.mul(1e+9)
```

Is there an explanation for ``.mul(1.0 - 1.0 / s[1]).mul(n)`` and ``.mul(1e+9)``? Thank you!

**Comment by jiecaoyu** [comment]
@ysymyth Please check [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/issues/28#issuecomment-401885963) and [here](https://github.com/jiecaoyu/XNOR-Net-PyTorch/issues/47).

**Comment by ysymyth** [comment]
Thank you!
