### ISSUE TITLE
Data broken

### ISSUE THREAD

**Issue by mingren200323** [jiecaoyu/XNOR-Net-PyTorch#73]
Hi, thank you for your impressing work. I have tried to download the Pretrained model from https://drive.google.com/open?id=0B-7I62GOSnZ8R3Jzd0ozdzlJUk0, but it seems that the data was broken and can't be unzipped. Please check it, thank you!

**Comment by jiecaoyu** [comment]
@mingren200323 you should be able to load the file by:

```bash
python main.py --pretrained models/LeNet_5.best.pth.tar --evaluate
```

This file does not require uncompressing.

**Comment by mingren200323** [comment]
And how can I convert it to some readable document， like txt or csv？



潘彪

北京航空航天大学 电子信息工程学院

博士后

地址：北京市海淀区学院路37号

电话：13552071783

On 7/10/2019 11:43，jiecaoyu<notifications@github.com> wrote：

@mingren200323 you should be able to load the file by:

python main.py --pretrained models/LeNet_5.best.pth.tar --evaluate

This file does not require uncompressing.

**Comment by jiecaoyu** [comment]
@mingren200323 you can load it using

```python
data = torch.load(file_path)['state_dict']
```
It gives a list of parameters.

**Comment by mingren200323** [comment]
Thank you for your immediate reponse! Since I am planning to write a paper with your pretrained models. I will acknowledge you in the paper. If you wish to cooperate, we can keep in touch by e-mail or wechat! I am one of the post-doc in Beihang University now and you can get my wechat directly from the phone number listed in the last message

**Comment by mingren200323** [comment]
emm sorry for another question, I have opened the tar file and seen the pretrained data. But I wonder why it is float type instead of +1/-1?

**Comment by jiecaoyu** [comment]
@mingren200323 The model is stored in floating numbers. If you need the binary values, you can load the pretrained data into the model with
```bash
python main.py --pretrained models/LeNet_5.best.pth.tar --evaluate
```
After the [binarization operation](https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/ebccb503b2f9ebc96187a75b6daa63d95b61d110/MNIST/main.py#L60), you can print out the parameters by

```python
for key, value in model.named_parameters():
    print(key, value)
```

All the weights have binary values of ```{-a, a}``` where ```a``` is a floating-point number. These weights can be considered as ```a x {-1, +1}```. Bias values are not binarized.
