### ISSUE TITLE
ImportError: No module named 'accimage'

### ISSUE THREAD

**Issue by gdelephant123** [jiecaoyu/XNOR-Net-PyTorch#74]
When I ran "python main.py" in /XNOR-Net-PyTorch-master/ImageNet/networks, it appeared ImportError: No module named 'accimage' in File "/usr/local/lib/python3.5/dist-packages/torchvision
/packages". That is to say, "import accimage" is wrong. How to solve this problem? thanks you.

**Comment by jiecaoyu** [comment]
You can delete that line or install [accimage](https://github.com/pytorch/accimage)

**Comment by gdelephant123** [comment]
> You can delete that line or install [accimage](https://github.com/pytorch/accimage)
Thanks.

**Comment by CrazyBrick** [comment]
> You can delete that line or install [accimage](https://github.com/pytorch/accimage)

 conda install -c conda-forge accimage
It's useful，thanks！
