### ISSUE TITLE
For ImageNet, why not use test dataset, only use validate data for test?

### ISSUE THREAD

**Issue by gdelephant123** [jiecaoyu/XNOR-Net-PyTorch#75]
@jiecaoyu

**Comment by jiecaoyu** [comment]
It is a conventional setting.

**Comment by gdelephant123** [comment]
> It is a conventional setting

Then what the value of test dataset?

**Comment by gdelephant123** [comment]
Then what the value of test dataset, but it really have test dataset. @jiecaoyu

**Comment by jiecaoyu** [comment]
@gdelephant123 It does have the test dataset. I have not tested the model on test dataset but I think you can try it. It should only require some changes in the validation dataset loading function.

**Comment by gdelephant123** [comment]
Thanks you. @jiecaoyu
