### ISSUE TITLE
Why ReLu?

### ISSUE THREAD

**Issue by penpaperkeycode** [jiecaoyu/XNOR-Net-PyTorch#76]
Hello, Thank you for your great work.

I have a question for you.

In 'nin.py' at Conv Module, 

def forward(self, x):
        x = self.bn(x)
        x, mean = BinActive()(x)
        if self.dropout_ratio!=0:
            x = self.dropout(x)
        x = self.conv(x)
        x = self.relu(x)     #why this relu needed? 
        return x

in my opinion, relu operation after conv makes minus term disregarded.  
if relu for the non-linearity, signum activation can help that part. 
then why relu is needed in this architecture?

**Comment by jiecaoyu** [comment]
@IntelligenceDatum It provides extra non-linearity in addition to the sign function. In practice, it can help slightly improve accuracy.

**Comment by penpaperkeycode** [comment]
Thank you for quick reply.
In that case, I understand including relu in the architecture. 

have a good day!
best regard :)
