### ISSUE TITLE
Why is there a relu in the forward function after the binActive?

### ISSUE THREAD

**Issue by lusensama** [jiecaoyu/XNOR-Net-PyTorch#79]
https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/ebccb503b2f9ebc96187a75b6daa63d95b61d110/ImageNet/networks/model_list/alexnet.py#L58
The original code does not seem to have the relu at the same stage. 
https://github.com/allenai/XNOR-Net/blob/4006d594fe0349a5ed4a5ba6795641d9eecb3aac/models/alexnetxnor.lua#L17
I don't know lua so please correct me if there is anything that I did not see.
Thanks.

**Comment by jiecaoyu** [comment]
@lusensama The original paper mentioned "We can insert a non-binary activation(e.g.,ReLU) after binary convolution. This helps when we use state-of-the-art networks (e.g.,AlexNet or VGG)."
