### ISSUE TITLE
Inconsistency in function "meancenterConvParams" and XNOR paper

### ISSUE THREAD

**Issue by XinDongol** [jiecaoyu/XNOR-Net-PyTorch#83]
https://github.com/jiecaoyu/XNOR-Net-PyTorch/blob/ebccb503b2f9ebc96187a75b6daa63d95b61d110/CIFAR_10/util.py#L39

Considering the dimension of weights' tensor for a layer 
![](https://i.loli.net/2020/02/26/VpinG8WeMIbUlTy.png)
, mean should be computed per out_channel instead of input_channel.

If my understanding is correct, this line should be
`negMean = self.target_modules[index].data.mean(0, keepdim=True).\ `

**Comment by jiecaoyu** [comment]
Hi @XinDongol ,  ```.mean(1, keepdim=True)``` will reduce the size of weights from ```(out_channels, in_channels/groups, kernel_size[0], kernel_size[1])``` to ```(out_channels, 1, kernel_size[0], kernel_size[1])```. It is calculating the mean per ```(out_channel, kernel_size[0], kernel_size[1])```

**Comment by XinDongol** [comment]
Thanks for your reply. 
Yes, you are right.  I was wondering why do not we reduce the size into `(out_channels, 1, 1, 1)`

**Comment by jiecaoyu** [comment]
@XinDongol Actually I cannot recall the details, I think I am following the original XNOR implementation since they didn't mention this operation in the original paper.
