### ISSUE TITLE
How can the Object 'bin_op' of Class 'BinOp' change the parameters 'weight' of network 'model' in your code? 

### ISSUE THREAD

**Issue by Jianglin954** [jiecaoyu/XNOR-Net-PyTorch#87]
Hi, thank you for your impressing work. I have some questions about this code.
What is the role of the object 'bin_op'? It seems that it can not change the parameters 'weight' of the network 'model'?  In the training process, it seems that all the parameters in network are not binary. All the calculated binary parameters are stored in 'bin_op.target_modules', but they are not used in the training process of the network 'model'. It looks like the training process only uses binary input but real weight. Do I misunderstand something? Thanks for your answer.

**Comment by jiecaoyu** [comment]
hi @LJL090504 , ```bin_op.target_modules``` are the weights tensors so the weights are binarized. The binary values are stored as floating-point numbers so we can use cuda kernels for faster training. As an example, binary values 0.5 x [-1, 1] are stored as [-0.5, 0.5].

**Comment by Jianglin954** [comment]
Thank you @jiecaoyu very much for your prompt reply. I understand that `bin_op.target_modules` are binary value, which are stored as floating-point numbers as the following attached picture. But I find that after the operation `bin_op.binarization()`, the weights `model.weight.data` are not binary values as can be seen from the following second picture. It seems that the forward propagation `output = model(data)` does not use binary weights to perform convolution. The binary weight values are only stored in `bin_op.target_modules` but not used in forward propagation. Do I misunderstand something? Thanks a lot.
![111](https://user-images.githubusercontent.com/63186596/78520850-8f6c7300-77fa-11ea-95c6-3fe38e666888.png)
![222](https://user-images.githubusercontent.com/63186596/78520864-998e7180-77fa-11ea-9dd6-7899108da07b.png)

**Comment by jiecaoyu** [comment]
Hi @LJL090504 , I wonder what parameter is ```model.weight.data```? I think you can access the weights of a module ```m``` by ```m.weight``` but I don't know what do you mean by ```model.weight```.
