### ISSUE TITLE
Requirements to run the code?

### ISSUE THREAD

**Issue by Yogeshyl07** [jiecaoyu/XNOR-Net-PyTorch#88]
I am trying to run this code , But facing syntax errors.
I believe there is a mismatch in version i am using with that of being used when this code was developed.

Can anybody please provide which version(requirements) should be used to do inference?

**Comment by jiecaoyu** [comment]
@Yogeshyl07 can you post the error message here?

**Comment by Yogeshyl07** [comment]
@jiecaoyu ,I was able to fix that issue . It was related to version mismatch . Using python 2.7 and pytorch 1.4 solved that issue .


But after I validate alexnet pretrained model I am getting precision value 0? 

 

` * Prec@1 0.000 Prec@5 0.000`

**Comment by Yogeshyl07** [comment]
@jiecaoyu ,I was able to solve that issue after I used python 2.7 and pytorch 1.4
I am facing a new problem , which I have explained below:

I had 10 images ,in 2 classes(5 each)of val folder
After I validate the pretrained Alexnet model, I printed output from model as well as the target tensor it was expecting ,but
precision remains 0, even after 9/10 predictions were correct? 
```
output_tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 1], device='cuda:0'))
('target is', tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], device='cuda:0'))

 * Prec@1 0.000 Prec@5 0.000
```
As far as understand 
Precision = (true-positives) /(true-positive + false-negatives )
What might be the reson ? Am I doing something wrong ?

**Comment by jiecaoyu** [comment]
@Yogeshyl07  could you share your entire code somewhere? Sorry but I cannot get enough information from your description.
