### ISSUE TITLE
Regarding the Classes of an Imagenet

### ISSUE THREAD

**Issue by Gangadhararamesh** [jiecaoyu/XNOR-Net-PyTorch#92]
Hi  @jiecaoyu ,

Can you please send me the list of the  Imagenet Classes  and its indices  which are used in  Alexnet Pretrained model for training

Thanking You

**Comment by jiecaoyu** [comment]
Hi @Gangadhararamesh , I did not have that data, but I think you could find that on the ImageNet website or by looking into the raw data.
