### ISSUE TITLE
Fully Connected Layer

### ISSUE THREAD

**Issue by yaduydk97** [jiecaoyu/XNOR-Net-PyTorch#94]
Is every input node multiplied with the same filter values or if each input node is multiplied with different sets of filter values?....
How FC is happening in this code?
@jiecaoyu Could you please explain it in detail

**Comment by jiecaoyu** [comment]
hi @yaduydk97 , I am not sure what do you mean by ```filter value```?

**Comment by yaduydk97** [comment]
Each input node in FC layer will be multiplied with weight values,is it so??
I want to know if each input node is multiplied with same set of weight.

Thank you @jiecaoyu  for your quick response

**Comment by jiecaoyu** [comment]
@yaduydk97 the computation of FC is still the same as the conventional FC. Only the value of weights/inputs are binarized.

**Comment by yaduydk97** [comment]
@jiecaoyu I would be more happy to know,how FC is binarized in your code??
Are you doing the same way like you did for other layers?(ie Binarizing input and weight then doing XNOR and the end result is multiplied with alpha)
